### PR TITLE
blue formatting with flake8 checks

### PR DESCRIPTION
**Pull request by vineetbansal**
**Either this PR or PR 177 should be merged**.

The entire codebase has been formatted with the [blue](https://pypi.org/project/blue/) formatter. 2 advantages (IMHO) that `blue` has over `black` are:
  - uses single quotes for strings as default instead of double quotes (easier on the eyes).
  - allows one to not have to stick to the 80 character width, which is too restrictive. I've never seen a good argument for the 80-character width limitation in this day and age (even when using the terminal extensively). I'm using a more liberal 120 character width here, which results in a LOT fewer lines of code.

Pre-commit hooks have been added to the code, and the CI will now automatically check for compliance by using `pre-commit run --all-files`, so developers are expected to do a `pre-commit install` to ensure that their pushed changes are not marked as failed by our CI. I've added all this information to the 'Developer Guidelines' wiki page.

The things our `pre-commit` will check for are:
  - Ensure there is no trailing whitespace on a line.
  - Make sure files end in a newline and only a newline.
  - Ensure code has no `flake8` errors.
  - Ensure code is `blue` formatted with a max `120` character line length.
  - Ensure imports are absolute (relative imports are MUCH harder to track down and refactor).
 
This is a minimal and reasonable place to start with I think. Of course we can add more checks (e.g. one of your students mentioned `isort`) in the future.

I've gone through the code and removed all the `flake8` errors (mostly having to do with unused imports, unused variables etc.). There are handful of places where I had to add a `#noqa` on a line to have it ignored by all this machinery. I'll open some new issues on those once this is merged.

**EDIT: I'm opening up a parallel [PR](https://github.com/zhonge/cryodrgn/pull/177) with black as the formatter. Only one of these two should be merged, based on your preference.

### CODE REVIEW

**Comment by adamlerer** [comment]
I am not opinionted on `black` vs `blue`, but I think that vscode support is a high priority (i.e. use auto-format on save in vscode) and I don't think vscode currently supports blue. Thoughts?

**Comment by adamlerer** [comment]
Justification for double-quoted strings:
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings

Justification for line length (88, not 120. 120 makes diff review and side-by-side editing hard on regular monitors)
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length

Again, I'm not personally opinionated but I really think there's a lot of value in using the most popular formatter that's integrated into more tools, and this is more important than opinionated debates over particular formatting choices.

**Comment by vineetbansal** [comment]
@adamlerer - not a problem. `blue` is preferred in my circles, but I'm only involved in this project for a few more months, while you will be working with the code for a lot longer :) As long as there's recognition that `black` is not the **standard** by any means just on account of being more popular (the circular argument is what I have a problem with), I'm fine going with `black`. As you suspect, it's important to have *some* standardization for `cryoDRGN` rather than spending time over the pros-cons.

Let me open up a parallel PR with `black` as the formatter. Once you or @zhonge merge any of the ones based on your preference, I'll kill the other PR.

**Comment by adamlerer** [comment]
Yeah, I didn't mean to imply that black is any universal standard, and I'm super unopinionated about specific style. My motivation is entirely about IDE integration, which personally I find super useful

https://test-black.readthedocs.io/en/latest/editor_integration.html

and I don't see something equivalent for `blue` (e.g. https://github.com/microsoft/vscode-python/issues/19186 ). Thanks for being flexible!

**Pull request closed without merging**
