### PR TITLE
eval_volume() mix float32 with float64

### PR DESCRIPTION
**Pull request by dongzhuoer**
dz is float64, then x becomes float64, so `self.forward(x)` throw error since model weights are float32

### CODE REVIEW

**Comment by zhonge** [comment]
Thanks! Can you provide an example of where you run into this error? Why is your dz a float64? It should already be type float32, so it would be good to find the source of the type mismatch.

**Comment by fredward** [comment]
I am running into the same issues trying to analyze a z dimension = 1 training run. 
I think, the issue seems to be the type inference of np.linspace 
eg:
`np.linspace(-extent,extent,D,endpoint=True)`
gives a float64 array on my machine

**Comment by fredward** [comment]
It's the same machine -- Ubuntu 16.04.

**Comment by zhonge** [comment]
What version of pytorch are you using? It would be helpful to get the full traceback. I've never run into this / can't reproduce. Thanks!

**Comment by fredward** [comment]
The full output from the command is below. I'm on pytorch 1.5.0 and CUDA 10.1.

I can get it to run no problem by specifying dtype=np.float32 in the linspace call.


```
cryodrgn analyze train_128_1_z1 49 --Apix  1.1136
2020-05-18 10:35:22     Saving results to /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/analyze.49
2020-05-18 10:35:23     Running command:
cryodrgn eval_vol /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/weights.49.pkl --config /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/config.pkl --zfile /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/analyze.49/z_values.txt -o /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/analyze.49 --Apix 1.1136
2020-05-18 10:35:26     Use cuda True
2020-05-18 10:35:26     Namespace(Apix=1.1136, D=128, config='/media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/config.pkl', domain='fourier', downsample=None, enc_mask=64, encode_mode='resid', flip=False, func=<function main at 0x7f024331f830>, l_extent=0.5, n=10, norm=[0, 322.7569], o='/media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/analyze.49', pdim=256, pe_type='geom_lowf', players=3, prefix='vol_', qdim=256, qlayers=3, verbose=False, weights='/media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/weights.49.pkl', z=None, z_end=None, z_start=None, zdim=1, zfile='/media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/analyze.49/z_values.txt')
2020-05-18 10:35:30     Using circular lattice with radius 64
2020-05-18 10:35:30     Loading weights from /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/weights.49.pkl
2020-05-18 10:35:30     Generating 10 volumes
2020-05-18 10:35:30     [-2.04078598]
Traceback (most recent call last):
  File "/EM/miniconda2/envs/cryodrgn/bin/cryodrgn", line 11, in <module>
    load_entry_point('cryodrgn==0.2.0', 'console_scripts', 'cryodrgn')()
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/__main__.py", line 50, in main
    args.func(args)
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/commands/eval_vol.py", line 123, in main
    vol = model.decoder.eval_volume(lattice.coords, lattice.D, lattice.extent, args.norm, zz) 
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/models.py", line 299, in eval_volume
    x = torch.cat((x,z), dim=-1)
RuntimeError: Expected object of scalar type double but got scalar type float for sequence element 1.
Traceback (most recent call last):
  File "/EM/miniconda2/envs/cryodrgn/bin/cryodrgn", line 11, in <module>
    load_entry_point('cryodrgn==0.2.0', 'console_scripts', 'cryodrgn')()
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/__main__.py", line 50, in main
    args.func(args)
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/commands/analyze.py", line 158, in main
    analyze_z1(z, outdir, vg)
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/commands/analyze.py", line 55, in analyze_z1
    vg.gen_volumes(outdir, ztraj)
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/commands/analyze.py", line 131, in gen_volumes
    analysis.gen_volumes(self.weights, self.config, zfile, outdir, **self.vol_args)
  File "/media/HDD2-8TB/fred/cryodrgn/cryodrgn/analysis.py", line 292, in gen_volumes
    return subprocess.check_call(cmd, shell=True)
  File "/EM/miniconda2/envs/cryodrgn/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cryodrgn eval_vol /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/weights.49.pkl --config /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/config.pkl --zfile /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/analyze.49/z_values.txt -o /media/HDD2-8TB/fred/cryodrgn/train_128_1_z1/analyze.49 --Apix 1.1136' returned non-zero exit status 1.
```

**Comment by zhonge** [comment]
Ah I see -- was able to reproduce with pytorch 1.5. It looks from the pytorch 1.5 release notes they made some backwards incompatible changes to the inferred dtype in tensor constructors from numpy. Thanks all!

**Pull request merged**
