### PR TITLE
Data Shuffler

### PR DESCRIPTION
**Pull request by adamlerer**
Implement a new type of data loader to speed up lazy loading. Instead of loading individual random images from disk (slow), it loads sequential chunks of size `batch_size` into an in-memory buffer (I used a buffer size of 32k images), and then reads batches randomly out of this buffer. This means that the data order is not completely random, but I think it's good enough.

For a dataset of 4.4M 128x128 images:

| Mode                        | hours/epoch |
|-----------------------------|------------|
| Eager                       | 1.5       |
| Eager (`--num-workers 1``)  | 0.75        |
| `--lazy` (`master`)         | 4+       |
| `--lazy` (`vb/imagesource`) | 4+       |
| Lazy `--shuffle-size=32768` (10k-image MRC files) | 1.5        |
| Lazy `--shuffle-size=32768` (1M-image MRC files) | 0.75        |

We originally hoped that `vb/imagesource` would speed up lazy loading, but it didn't, and after much profiling I determined the bottleneck is just # of random reads, which seems to be throttled on GPFS even though I think it's flash storage.

Playbook for lazy loading (based on the Princeton cluster):
1. Set `--shuffler-size=32768` or thereabouts
2. Make sure your dataset is not split into too many tiny files. I got 2x speedup when using 4 files with 1M images each, vs 400 files with 10k images each. You can resplit the files using `cryodrgn downsample <dataset> -D <orig_size> --chunk <big_number>`.
3. The images have to be sequential so you can load sequential chunks. Therefore, you can't use the `--ind` argument.

Still todo:
[ ] Incorporate into scripts other than `train_vae`.
[ ] Support chunk sizes other than `batch_size` (should we?)
[ ] Add unit test that it actualy samples everything from the dataset exactly once.
[ ] Make multithreaded?

### CODE REVIEW

**Comment by vineetbansal** [comment]
Thanks @adamlerer - this is great!
The one question I have here is the introduction of `get_slice` in `ImageSource` - the `images()` method is already capable of dealing with slices (we can add a `start`/`stop` if we don't want a full slice support, or support that in addition to the slice), so I'm not seeing why this needs to be introduced there.

As for the matter of `ImageSource` classes dealing *efficiently* with contiguous slices, we can do something there (issue #229 was meant to address what you're now doing in `get_slice`, for example). The sub-classes could do the most efficient thing they can (the DataFrame-based subclasses will already do this, but the MRCS subclass will not), and/or throw a warning.

**Comment by vineetbansal** [comment]
> 1. I wanted a separate code path to avoid interacting with your `images()` code.

Why? You don't have to modify (if that's what you mean by interact) `images()` at all, just use it.

> 2. I like being explicit about functionality. I'd rather have separate functions `get_slice()` and `get_indices()`. I explicitly _don't_ want `ImageSource` subclasses to silently fall back on an inefficient slice-get, because then the user will see slow loading perf and have to dig deep in the code to understand why. I'd rather the code just fail and say "You can't use the fast data shuffler because this data source doesn't allow for contiguous slice reads."

Fair point, but there are other ways of being explicit (like using the `is_contiguous` flag idea like I mentioned above) at a higher abstraction level than the `ImageSource` class. Conceptually even if you do need a new method it should be nothing more than:

```
def get_slice(self, start, stop):
  assert self.is_contiguous, "Operation only available on contiguous sources"
  return self.images(np.array(start, stop))
```

**Comment by vineetbansal** [comment]
Eventually, I think having two parallel implementations like this (one that is general and another that is specific) is a problem. In this case, the first could be modified to take in a flag that insists that there be a single group:

```
    def _images(self, indices: np.ndarray):
        def load_single_mrcs(filepath, df):
            src = MRCFileSource(filepath)
            # df.index indicates the positions where the data needs to be inserted -> return for use by caller
            return df.index, src._images(df["__mrc_index"])

        data = np.zeros((len(indices), self.D, self.D), dtype=self.dtype)

        # Create a DataFrame corresponding to the indices we're interested in
        batch_df = self.df.iloc[indices].reset_index(drop=True)
        groups = batch_df.groupby("__mrc_filepath")
        n_workers = min(self.n_workers, len(groups))

        with futures.ThreadPoolExecutor(n_workers) as executor:
            to_do = []
            for filepath, _df in groups:
                future = executor.submit(load_single_mrcs, filepath, _df)
                to_do.append(future)

            for future in futures.as_completed(to_do):
                data_indices, _data = future.result()
                for idx, d in enumerate(data_indices):
                    data[d] = _data[idx, :, :] if _data.ndim == 3 else _data

        return data

    def get_slice(self, start: int, stop: int) -> np.ndarray:
        # FIXME: I'm not sure if this is going to be too slow due to the panda ops and
        # constructing MRCFileSource's every time.
        # I've only profiled the TxtFileSource dataset.
        batch_df = self.df.iloc[start:stop].reset_index(drop=True)
        groups = batch_df.groupby("__mrc_filepath")
        if len(groups) > 2:
            raise ValueError("You're doing something dumb... either your particle list is not contiguous or you've split it into too small files.")
        ret = []
        for filepath, group in groups:
            n = len(group)
            src = MRCFileSource(str(filepath))
            idx = group["__mrc_index"].to_numpy()
            start = idx[0]
            if not all(idx == np.arange(start, start + n)):
                raise ValueError("Can't efficiently load a slice of a non-contiguous particle list")
            ret.append(src.get_slice(start, start + n))
        ret = np.concatenate(ret, axis=0) if len(ret) > 1 else ret[0]
        assert len(ret) == stop - start, (len(ret), start, stop)
        return ret
```

**Comment by adamlerer** [comment]
> Eventually, I think having two parallel implementations like this (one that is general and another that is specific) is a problem.

I'm not sure what you're objecting to here. Ultimately, we sometimes need to ask for a slice and sometimes a set of indices. Are you objecting to having two different *implementations* or to having two different *function names*? These are orthogonal questions.

Two different implementations is necessary for performance reasons.

Two different function names is an aesthetic choice, I don't think it really matters although I prefer it.

**Comment by vineetbansal** [comment]
The parallel implementation is indeed what I'm objecting to. I might be missing something, but I'm not seeing why the following is true:
```
Two different implementations is necessary for performance reasons.
```
If instead of `images(indices)` we had:
```
images(indices, insist_contiguous=False)  # I'm making this up
```
which does the most efficient thing possible (and throws an error if it can't), couldn't you use it for your use case with `insist_contiguous=True`?

Sorry for getting in the weeds a bit on this, but it's not just a matter of naming, but the only place where this matters is the actual MRC reading logic, and it could be trivially implemented as follows, and a lot of code duplication (between `get_slice` and `images`) thus avoided:
```
            is_contiguous = np.all(indices == indices[0] + np.arange(len(indices)))
            if insist_contiguous:
                assert is_contiguous, "MRC indices are not contiguous."

            if is_contiguous:
                f.seek(self.start)
                offset = indices[0] * self.stride
                # 'offset' in the call below is w.r.t the current position of f
                _data = np.fromfile(
                    f, dtype=self.dtype, count=self.size * len(indices), offset=offset
                ).reshape(-1, self.ny, self.nx)
                data[tgt_indices, ...] = _data
            else:
                for index, tgt_index in zip(indices, tgt_indices):
                    f.seek(self.start)
                    offset = index * self.stride
                    # 'offset' in the call below is w.r.t the current position of f
                    _data = np.fromfile(
                        f, dtype=self.dtype, count=self.size, offset=offset
                    ).reshape(self.ny, self.nx)
                    data[tgt_index, ...] = _data
```

The rest of the places you have `get_slice` is simply error checking on indices that shouldn't exist (because only `MRCFileSource` should be doing this error checking because that's where it matters), and _can_ only exist because you've taken off support for `--ind`. All other classes should simply pass this error checking to the underlying `MRCFileSource`.

Going this way also gets you back `--ind` support for free.

A lot of this might be obscured in the current code on account of `ThreadPoolExecutor`, but I feel the thinking is to take off all that stuff anyway.

**Comment by adamlerer** [comment]
Well, `if_contiguous: ... else: ...` is what I mean by two different implementations.

I'm fine with the refactor you're suggesting; do you want to go ahead and do that? You can merge `data-shuffler` into `vb/imagesource` and do the refactor on that branch if you want. But lets get this cleaned up and merged by the end of the week.

**Comment by vineetbansal** [comment]
Sounds good. I don't want to hold up the merge on these nitpicks (minor relative to what has been achieved here). I'll send other PR(s) with the refactors I'm suggesting.

**Pull request merged**
